name: strategy_forge_example
description: Example app for the Strategy Forge editor package.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"
dependencies:
  flutter:
    sdk: flutter
  strategy_forge:
    path: ..
  public_file_saver: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/rinks/
